### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ora#1]
Open for ideas/help on the best ways to test something like this.

https://github.com/sindresorhus/ora/blob/2a1820f3392339a70292a02875b46027a13d868b/test.js

**Comment by developit** [comment]
Not sure if this is useful, but:
https://gist.github.com/developit/ff98fa3df960d92f3024

**Comment by sindresorhus** [comment]
@developit Did you mean to post this in https://github.com/sindresorhus/cli-spinners/issues/4?
