### ISSUE TITLE
Spinner freezes if using an Observable

### ISSUE THREAD

**Issue by Shawn-ubiquisoft** [sindresorhus/ora#113]
Hi,

I'm running this on macosx, nodeJs version 10.15.3.  When I run the following code, the spinner freezes, and nothing happens until the observable returned from `new StagingCheckFragment().run()` actually completes.

Is this expected behavior?  Is it possible to use the spinner with an observable like this?  Any other ways to sync the spinner to a value that may update multiple times?

Thanks

```

/*--- check zip goes to staging --*/
    let spinner:any = ora(this.$msgs.staging_check).start();
    await new StagingCheckFragment().run(args.testKey, {})
      .subscribe(
        result => {

          if(result.success < 0){
            spinner.warn(this.$msgs.staging_check + colors.yellow('Not found.  (ignore if subsequent tests pass)'));
          } else if (result.success === 0){
            spinner.text = (this.$msgs.staging_check + `checked ${result.iteration} times`);
          } else {
            spinner.succeed(this.$msgs.staging_check + colors.green('PASS'));
          }
      });

```

**Comment by sindresorhus** [comment]
JavaScript is single-threaded and Observables can be both sync and async, so I assume the problem is that your Observable blocks the thread, which means the Ora spinner stops spinning.
