### ISSUE TITLE
stop or clear not work in Windows cmd

### ISSUE THREAD

**Issue by liudonghua123** [sindresorhus/ora#118]
Some pieces of code I wrote like the following, but whether I invoke stop or clear or not, the displayed text not cleared.
```js
    const vulnerable = await isVulnerable(url);
    const spinner = ora(
      `Detecting (${i}/${domains.length}) ${chalk.green(url)}`
    ).start();
    if (vulnerable) {
      spinner.stopAndPersist({
        symbol: '✖',
        text: `${domain} has vulnerability`,
      });
    } else {
      spinner.stop();
    }
```
![image](https://user-images.githubusercontent.com/2276718/59662377-603f3380-91df-11e9-8329-a7d26dd35732.png)

**Comment by sindresorhus** [comment]
We are just using normal ansi escapes, so this is probably a limitation in the VS Code console. You should open an issue about this on the VS Code issue tracker instead.

**Comment by liudonghua123** [comment]
After read the code, I found the `isEnabled` option is false in cmd or powershell environment, so If I want to make it work in these environments, I need to add `isEnabled: true` option during contruct ora instance.

If the `isEnabled` is false, then the excutaion of `start` will return early, `this.id = setInterval(this.render.bind(this), this.interval);` will never execute.

https://github.com/sindresorhus/ora/blob/5be19fc3fef5ca892facaecd81dadd661c5493ea/index.js#L98-L134

https://github.com/sindresorhus/ora/blob/5be19fc3fef5ca892facaecd81dadd661c5493ea/index.js#L293-L327
