### ISSUE TITLE
Undesirable space before spinner symbol when prefixText is empty string

### ISSUE THREAD

**Issue by ngocdaothanh** [sindresorhus/ora#122]
I set `prefixText` like this:

```js
spinner.prefixText = 'Loading';
spinner.spinner = 'simpleDots';
spinner.start();
...
spinner.stop();
```

Then, I set `prefixText` to an empty string and reuse the `spinner`:

```js
spinner.prefixText = '';
spinner.spinner = 'dots';
spinner.start();
```

This time, before the spinner symbol, there's one undesirable space.

The cause is this code in the `frame` method (https://github.com/sindresorhus/ora/blob/master/index.js#L119):

```
const fullPrefixText = typeof this.prefixText === 'string' ? this.prefixText + ' ' : '';
```

Initially, `prefixText` is `undefined` so the code worked. But after it's set to an empty string, it doesn't work as expected.

I'm using TypeScript. Setting like this will cause syntax error (https://github.com/sindresorhus/ora/blob/master/index.d.ts#L127):

```js
spinner.prefixText = undefined;
```

I have to do like this (not very nice):

```ts
this.spinner.prefixText = undefined as any;
```

**Comment by sindresorhus** [comment]
// @stroncium

**Comment by stroncium** [comment]
If we check for empty string here, it will be impossible to maintain consistent behavior(which is having the space). So, the options are:
 - remove default space and require users to pass full prefix(with space)
 - allow `undefined` as value

Implemented 2nd option for now.

@sindresorhus
