### ISSUE TITLE
Also update spinner interval when spinner is updated

### ISSUE THREAD

**Issue by ngocdaothanh** [sindresorhus/ora#123]
Currently, the interval is set only once at the constructor:

```js
this.interval = this.options.interval || this.spinner.interval || 100;
```

It should also be updated at `set spinner(spinner)`.

**Comment by sindresorhus** [comment]
Yeah, we missed this in https://github.com/sindresorhus/ora/commit/2aee2da48286edfef27f9baf1dcf7861a099993b.

// @jeetiss

**Comment by jeetiss** [comment]
I did it 🙌🏻

**Comment by ngocdaothanh** [comment]
@jeetiss @sindresorhus Thanks for fixing! Can you release a new version please?

I'm using TypeScript.
Currently I have to use this dirty patch:

```
const spinner = ora();
spinner.spinner = 'monkey';
(spinner as any).interval = (spinner.spinner as any).interval;
```

**Comment by sindresorhus** [comment]
New release is out: https://github.com/sindresorhus/ora/releases/tag/v4.0.0
