### ISSUE TITLE
Interval is not updated when spinner is updated by name

### ISSUE THREAD

**Issue by ngocdaothanh** [sindresorhus/ora#127]
Previous report:
https://github.com/sindresorhus/ora/issues/123

Unfortunately, the fix:
https://github.com/sindresorhus/ora/pull/125/files

only handles the case when spinner is updated by an object.

When it's updated like this, the interval won't be update:

```
const spinner = ora();
spinner.spinner = 'dots';
spinner.spinner = 'monkey';
```

**Comment by sindresorhus** [comment]
// @jeetiss

**Comment by jeetiss** [comment]
oh, noo 🙀

**Comment by jeetiss** [comment]
Sorry, I don't dived enough with first pull request.
Solution is covering all cases now
