### ISSUE TITLE
4.0.x crashes with 'Cannot read property 'apply' of undefined' 

### ISSUE THREAD

**Issue by swernerx** [sindresorhus/ora#133]
I am using Ora inside [Preppy](https://github.com/sebastian-software/preppy#readme). Unfortunately updating to 4.0.x seems to break in some cases with the following error

`TypeError: Cannot read property 'apply' of undefined:`

```
Stack Trace:
  - ~/ora/index.js:236 emit()
  - _stream_readable.js:964 pause()
  - ~/ora/index.js:247 stopDiscardingStdin()
  - ~/ora/index.js:209 stop()
  - ~/preppy/bin/preppy:399 buildEnd()
  - ~/rollup/dist/rollup.js:16616 then()
```

Probably we should add another if-block to check whether the `_stdinOldEmit` is still defined.

Any help would be appreciated.

**Comment by sindresorhus** [comment]
// @stroncium

**Comment by stroncium** [comment]
@swernerx Can you tell me how to reproduce this(file structure + command for preppy is ok)?
Weird thing is we do ```js
if (this._stdinOldEmitOwnProperty) {
	stdin.emit = this._stdinOldEmit;
} else {
	delete stdin.emit;
}

this._stdinOldRawMode = undefined;
this._stdinOldEmit = undefined;
this._stdinOldEmitOwnProperty = undefined;
```

so it shouldn't be possible out version of `stream.emit` is called after `_stdinOldEmit` was unset.

**Comment by swernerx** [comment]
That's probably a tricky one because I don't see it everywhere... today I had it in one of my other OSS projects. Here is the branch which fails: https://github.com/sebastian-software/universal-dotenv/tree/ora-issue-133 to execute `npm test`.

**Comment by stroncium** [comment]
@swernerx Ok, so I traced the problem. `ora` doesn't support multiple spinners running simultaneously, and that's what happens in your case.

I think I should be able to fix this exact problem to at least make it to not crash, but you probably should change your code as well, as `ora` spinners are not expected to be displayed properly anyway.

**Comment by swernerx** [comment]
Did not know that it is not meant to run in parallel... that's a pity. I will probably check how I can revamp what's implemented in Preppy.

**Comment by stroncium** [comment]
@swernerx Well, it's not really mission critical if there will be minor glitches, so maybe it will work for you just as it is. Tbh, I didn't notice any while testing, so maybe it works good enough for you. It's just that it isn't officially supported as far as I know.
