### ISSUE TITLE
Process gets stuck when v4.0.2 is used with Inquirer library

### ISSUE THREAD

**Issue by ngocdaothanh** [sindresorhus/ora#134]
Inquirer: https://github.com/SBoudrias/Inquirer.js

Program to demonstrate the problem:

```js
const inquirer = require('inquirer');
const ora = require('ora');

async function prompt() {
  await inquirer.prompt([
    {
      type: 'input',
      name: 'text',
      message: 'Input text'
    }
  ]);
}

async function spin() {
  const spinner = ora();
  spinner.start('Spinning');
  return new Promise((resolve) => {
    setTimeout(() => {
      spinner.succeed();
      resolve();
    }, 1000);
  });
}

async function main() {
  await prompt();
  await spin();
  console.log('End of main, should exit');
}
main();
```

Example output (on Mac, Node v12.8.0):

```
? Input text 
✔ Spinning
End of main, should exit
^C
```

At the end of the program, the program cannot exit, I have to press Ctrl+C.

Notes:

v4.0.1 doesn't have the problem! So the problem comes from this commit: https://github.com/sindresorhus/ora/commit/17761e99376e497c7fa66af3551f94efcad004c7

When changing the order (putting `await spin()` before `await prompt()`), the program can exit normally. So it seems that ora was messing with stdio, and Inquirer could clean up for ora.

[wftnode](https://github.com/myndzi/wtfnode) shows that at the end of the program, there are still active handles, causing the process to get stuck:

```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
  - fd 0 (tty)
```

Proposed solution:
As I understand, Inquirer uses Node's standard [readline](https://nodejs.org/api/readline.html) API. So instead of messing directly with the stdio, to be more reliable ora may also try using readline.

**Comment by ngocdaothanh** [comment]
After reading [Inquirer's source code](https://github.com/SBoudrias/Inquirer.js/blob/master/packages/core/hooks.js), I think ora can use [mute-stream](https://github.com/npm/mute-stream) and [readline](https://nodejs.org/api/readline.html) like this:

```js
const MuteStream = require('mute-stream');
const readline = require('readline');

// Demo SIGINT
process.on('SIGINT', function() {
  console.log('On SIGINT');
});

async function discard() {
  return new Promise((resolve) => {
    const output = new MuteStream();
    output.pipe(process.stdout);
    output.mute();

    const rl = readline.createInterface({
      input: process.stdin,
      output
    });

    rl.on('SIGINT', async () => {
      rl.close();
      process.kill(process.pid, 'SIGINT');
      resolve();
    });
  });
}

async function main() {
  await discard();
  console.log('After discard');

  // Allow "Demo SIGINT" to run,
  // otherwise the process may exit before the demo runs
  setTimeout(() => {}, 0);
}
main();
```

Output:

```
<-- Type anything, it won't be output
After discard
On SIGINT
<-- It won't be output here either
```

**Comment by stroncium** [comment]
@ngocdaothanh This code hangs `ora` too.

**Comment by frank-orellana** [comment]
Can confirm this is happening to me. it causes the [framework7 cli](https://github.com/framework7io/framework7-cli/issues/49) to hang but only on windows. After reverting to 3.4.0 it worked without any problem.

It also worked fine on the same computer but using ubuntu for windows.

**Comment by ngocdaothanh** [comment]
> This code hangs ora too.

I was using Node 12.8.0 on Mac 10.15.

**Comment by ngocdaothanh** [comment]
> This code hangs ora too.

To avoid confusion:

I posted 2 code snippets:
* Code 1 should hang (pressing Ctrl+C doesn't exit the program).
* Code 2 should not hang (pressing Ctrl+C exits the program).

I was using Node 12.8.0 on Mac 10.15.

**Comment by stroncium** [comment]
2nd piece of code hangs under windows when integrated into ora.
```
The hanging is not related to event loop nor ora code on it's own. ora uses cli-cursor which uses restore-cursor, which uses signal-exit to write to stderr on exit. This line to write to stderr never finishes(properly hangs)
```
https://github.com/sindresorhus/ora/issues/132#issuecomment-538664044

**Comment by michaelw85** [comment]
For me setting `discardStdin: false` resolved the freezing, not perfect but at least a workable solution.

**Comment by 190km** [comment]
- [ ] @ #> [**_`_****_`_**](### url)hey
