### ISSUE TITLE
terminal always get stuck when use ora in aync function

### ISSUE THREAD

**Issue by lronelove** [sindresorhus/ora#136]
When I use ora in async function, such as 'setTimeout' or 'Promise',  the terminal will get stuck, I can not use the terminal agin.

**Comment by mskian** [comment]
Same issue I am too facing on Windows 10 CMD
No issues Linux Terminal

**Comment by michaelw85** [comment]
I think this is related to #134 

@lronelove For me setting `discardStdin: false` resolved the freezing, not perfect but at least a workable solution.

**Comment by lronelove** [comment]
> I think this is related to #134
> 
> @lronelove For me setting `discardStdin: false` resolved the freezing, not perfect but at least a workable solution.

yes, you are right. using 'discardStdin: false' can fix this problem.
thank you~

**Comment by abhijithvijayan** [comment]
can confirm this on [line](https://github.com/abhijithvijayan/create-remote-repo-cli/blob/a577847b0ffe453e1ba34a8695686ae711ffb4b4/app/cli.js#L51) for [create-remote-repo-cli](https://github.com/abhijithvijayan/create-remote-repo-cli)
