### ISSUE TITLE
Showing percentage while tasks being installed

### ISSUE THREAD

**Issue by kruzus** [sindresorhus/ora#138]
Hello, sorry I am pretty new here so I'll keep this simple if possible. 

Is there a way to display percentage on items being installed? I joined this group and I wanted to contribute and I notice while you use their CLI,  during the installation there is no loading bar or % of any sort. There is only spinner and that is it. 

`const install = new ora({
  text: 'Installing package(s)...',
  install: process.argv[2],
  indent: 1,
  spinner: {
    "interval": 100,
		"frames": [
			"◜",
			"◠",
			"◝",
			"◞",
			"◡",
			"◟"
		]
  }
})`

I am trying to figure out where I could integrate this progress bar or % at least. 

I can provide more details if I confused anyone, thanks in advance! 

Cheers!

**Comment by sindresorhus** [comment]
How do you get the progress info? If you get the progress from an event, you could just set the `.text` property:

```js
yourProject.on('progress', percent => {
	ora.text = `${percent}% Loading unicorns`;
});
```

What would you like the final output to look like?
