### ISSUE TITLE
Improve Windows support

### ISSUE THREAD

**Issue by MarkTiedemann** [sindresorhus/ora#14]
I like ora, but I dislike that it defaults to the simple `line` spinner if `process.platform == 'win32'` since most alternative Windows terminals do support the other more elegant spinners, too.

I have started working on [windows terminal detection](https://github.com/MarkTiedemann/win-term) and have quickly tested which terminals support the default `dots` spinner (`cmder`, `conemu` and `mingw` support it; `cmd`, `powershell` and `cygwin` don't).

I know my findings are just exploratory yet and I know it's a niche, but is this something that you would consider to implement in ora? If so, well, I'd like to help out and continue my work. :)

**Comment by sindresorhus** [comment]
I don't really see the point. You now have [Bash for Windows](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/) which solves all of these problems. I'd be happy to add an override for it if someone using it could share the output of `$ node -p process.env`.

**Comment by guybedford** [comment]
I've found the best thing for windows support given this limitation is just to manually set the `spinner` object with frames that are cross-platform.
