### ISSUE TITLE
Flickering while spinning (windows terminal)

### ISSUE THREAD

**Issue by Boorj** [sindresorhus/ora#140]
Spinner is flickering while spinning. In most cases (single line + all frames same width) it's enough to remove `this.stream.clearLine();` here: 
https://github.com/sindresorhus/ora/blob/master/index.js#L231

If frame renders this: `fullPrefixText + frame + fullText`. Both texts are static, so seems that `clearLine` is required for those specific cases, when frame width differs.

Suggestion: add an option, that disables `this.stream.clearLine()` call.

**Comment by sindresorhus** [comment]
What terminal, Node.js version, and OS?

**Comment by sindresorhus** [comment]
> Suggestion: add an option, that disables this.stream.clearLine() call.

I'm unlikely to add that. However, maybe there's some kind of rendering optimization that can be done by default.

**Comment by Boorj** [comment]
Nodejs version, using windows terminal. Obviously, flickering appears because of delay clearing and rendering line again. Or slow refresh rate.
Probably, rendering optimization could be strings + lines number comparison between frames.
Anyway, my temporary dirty hack was (edited inside node_modules): 
- remove `clearLine` in rendering phase;
- add `clearLine` in `stopAndPersist`.

**Comment by sindresorhus** [comment]
By "windows terminal", do you mean cmd.exe or the new Windows Terminal? And **what** Node.js version?

**Comment by Boorj** [comment]
config: 
> node -v :  v13.5.0
 https://github.com/Microsoft/Terminal
![image](https://user-images.githubusercontent.com/2145313/72677110-637b0480-3acb-11ea-9794-42c3c2d08cc5.png)


Acrylic bg is turned off. Both tested with powershell and cmd.


Btw, today, using nest.js also found the same effect. That made me check out here: [nest-cli](https://github.com/nestjs/nest-cli/blob/master/lib/package-managers/abstract.package-manager.ts#L4) and ensure that it's also using `'ora'`.
Sorry, gif-recorder's refresh rate doesn't allow to display flickering in realtime (around 10 times per second), but as you can see some frames are missing:
![flickering](https://user-images.githubusercontent.com/2145313/72677088-2282f000-3acb-11ea-9c57-7322d1a382a3.gif)

1. `cmd.exe` running in personal window (not using terminal) doesn't cause any flickering issues. 
2. running with `conemu` doesn't cause any problems too:
![image](https://user-images.githubusercontent.com/2145313/72677204-67f3ed00-3acc-11ea-9aa0-b586b25b4def.png)

**Comment by sindresorhus** [comment]
Can you open an issue on https://github.com/microsoft/terminal ? This should definitely be fixed by the Windows Terminal team. I'm going to close as it's not something I'm interested in working around in the meantime.

**Comment by Boorj** [comment]
ok, sure

**Comment by benjamincburns** [comment]
@sindresorhus I'm afraid that this is likely a limitation of Electron-based terminals, as I'm experiencing the same issue on Terminus, which is also an Electron app... Is @Boorj's fix risky for some reason? If not, would you accept a PR for it?

**Comment by benjamincburns** [comment]
Oh my bad, turns out the Windows Terminal isn't an Electron app. Regardless, my question remains.

**Comment by sindresorhus** [comment]
A **good** pull request with rendering optimizations is welcome.
