### ISSUE TITLE
Animated SVG in Readme not loading on NPM page

### ISSUE THREAD

**Issue by mic-max** [sindresorhus/ora#141]
Works fine on Github. Maybe use a gif instead since that's what fast-cli does and that works on both sites.

![image](https://user-images.githubusercontent.com/15165028/75640445-fe4a2100-5be9-11ea-91ee-fb6e873a281e.png)

**Comment by sindresorhus** [comment]
This is a bug in the npm website: https://github.com/npm/marky-markdown/issues/437 I have no intention on working around their crappy site, so it will stay like this until they fix it, if they ever will. 🤷‍♂️
