### ISSUE TITLE
Spinner will freezes when I use Ora in my async functio.

### ISSUE THREAD

**Issue by fuergaosi233** [sindresorhus/ora#142]
```js
async function loader(fn,process,...args){
// process:{start,loding,sucess} runtime info 
  const spinner =  ora(process.start||`start`).start();
  spinner.text = `${process.loding||'loding'}`;
  try{
    let res = await fn(...args)
    spinner.succeed(process.success||`success`)
    return res 
  }catch(err){
    spinner.fail(process.fail||'fail');
    throw err;
  }
}
```
When i use` loader` to run async function , the spinner will freezes likes this:
![image](https://user-images.githubusercontent.com/22197568/75701726-371fee00-5cef-11ea-9393-e63ac18ef446.png)
So what should I do for solve this problem.

**Comment by fuergaosi233** [comment]
I change my sync function to async function then solved it.

**Comment by sindresorhus** [comment]
This is documented in the readme (at the bottom).
