### ISSUE TITLE
Change text on succeed()

### ISSUE THREAD

**Issue by sebastiantf** [sindresorhus/ora#144]
Is there any way to change the text when we call `.succeed()` so that when the spinner succeeds and green tick mark is shown, the text is changed to a success message.

Right now, I'm using `stopAndPersist()` as below:
```js
    const spinner = ora(`Doing something...`).start();

    // Do something async...
    await doSomething();

    spinner.stopAndPersist({
        symbol: colors.green("✔"),
        text: "Successfully backed up .git",
    });
```

Is this the only way to achieve what I want, or am I missing something?

If this is the only way, it would be nice to have this functionality (to change the text on success) built into `succeed()`

**Comment by sindresorhus** [comment]
`.succeed()` accepts a `text` argument.

**Comment by sebastiantf** [comment]
Yes I used that too but it didn't seem to change the text at the time I opened this issue. I think it must've been because I wasn't doing an async operation at that time.

Closing this then.
