### ISSUE TITLE
Ability to conditionally disable ora?

### ISSUE THREAD

**Issue by ktalebian** [sindresorhus/ora#147]
I want to provide a `--quiet` mode to my CLI; when this runs, I don't want any text to be outputted to the terminal. Is there an option to fully disable ora so nothing is displayed?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ora#isenabled

**Comment by ktalebian** [comment]
@sindresorhus but from the doc 

> Note that {isEnabled: false} doesn't mean it won't output anything. It just means it won't output the spinner, colors, and other ansi escape codes. It will still log text.

I did try the `isEnabled`; it still shows the text, but has no animation. I literally don't want to see any text printed to the screen.

**Comment by sindresorhus** [comment]
I guess we could add a `.isSilent` option and instance getter/setter.

As a workaround for now, you could pass in a stream to the `stream` option that does nothing with the output.
