### ISSUE TITLE
ES2015ify

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ora#15]
I think it would be nice if we ES2015ified `ora`. We could use classes and clean up the code. Supporting node 0.10 and 0.12 for CLI stuff isn't necessary anymore in my opinion.

**Comment by sindresorhus** [comment]
I want to do this, but I think it's better to wait a couple of months. There are a lot of users of this module and some might have CLI and API in the same package. I'll keep this open until such time.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ora/commit/86f747ea4ad57f6b0df60560aea18acdabf7493f
