### ISSUE TITLE
4.1.0 is a breaking change

### ISSUE THREAD

**Issue by vinyldarkscratch** [sindresorhus/ora#152]
Some of the dependencies that were updated in 4.1.0 present breaking changes, specifically that they dropped NodeJS v8 support (which both violates semver rules and poses an incompatibility issue since this repo is marked as supporting NodeJS v8).  Namely, [Chalk 4.0.0](https://github.com/chalk/chalk/releases/tag/v4.0.0), [log-symbols 4.0.0](https://github.com/sindresorhus/log-symbols/releases/tag/v4.0.0), and [tsd](https://github.com/SamVerschueren/tsd/releases/tag/v0.13.0) all dropped support for NodeJS v10.

**Comment by sindresorhus** [comment]
Reverted and released as a major version instead.
