### ISSUE TITLE
Can't make the spinner work

### ISSUE THREAD

**Issue by JuzouSatoru2** [sindresorhus/ora#153]
I tried to add ora in my cli but whatever I do the spinner is just kinda stuck.
The code can be found [here](https://github.com/JuzouSatoru2/create-nextjs-project/blob/master/index.js).
I'd love if someone could help me with my mistakes.

**Comment by sindresorhus** [comment]
This is answered in the readme: https://github.com/sindresorhus/ora#why-does-the-spinner-freeze
