### ISSUE TITLE
Blinking on Windows

### ISSUE THREAD

**Issue by ffMathy** [sindresorhus/ora#160]
While spinning, the whole text (including the spinner itself) blinks on Windows.

Tested in `cmd`.

**Comment by sindresorhus** [comment]
That's just `cmd` being slow. Not much we can do about that. I would recommend switching to Windows Terminal.

**Comment by ffMathy** [comment]
How does Docker do it then when showing its progress bar and pulling images?

It doesn't blink at all. Neither does `webpack` etc.

**Comment by cossssmin** [comment]
It blinks for me in both Windows Terminal and in Git Bash.

**Comment by altano** [comment]
I am seeing blinking in Windows Terminal as well, when SSHed into my Ubuntu server: 

https://user-images.githubusercontent.com/1009/130723893-b95933fd-e3ef-48fc-ab91-36d289f250a4.mp4

**Comment by WakerCN** [comment]
did anyone resolve blink in windows terminal?
