### ISSUE TITLE
Suggestion: promise enhancements

### ISSUE THREAD

**Issue by sarink** [sindresorhus/ora#169]
I often want to display different text based on the result of the `promise` (whether success or failure). Sometimes my `action` is multiple promises, so it would be convenient if the signature for that was `() => Promise` (so that I don't need to do create a new named variable for my promise on the line before it, and then pass it to ora). Lastly, it seems a lot more convenient to return the promise, rather than the spinner instance.

I've been using this little wrapper
```js
  const oraPromise = async <T>(
    action: () => Promise<T>,
    options: {
      startText?: () => string;
      successText?: (resp: T) => string;
      failText?: (err: Error) => string;
    } = {}
  ): Promise<T> => {
    const spinner = ora();
    const { startText, successText, failText } = options;
    if (startText) spinner.start(startText());
    return action()
      .then((resp) => {
        if (successText) spinner.succeed(successText(resp));
        return resp;
      })
      .catch((err) => {
        if (failText) spinner.fail(failText(err));
        throw err;
      });
  };
```
I think it enhances the usability of `promise` for some common cases. If you think it's worthwhile, I may be able to find time to submit a PR.

example:
```js
  // before
  await Promise.all(
    actions.map((name) => {
      const myAction = doSomeAsyncThing(name);
      const spinner = ora.promise(myAction, `Performing async action ${name}...`);
      myAction
        .then((result) => {
          spinner.succeed(`Success! ${result}`);
        })
        .catch((err) => {
          spinner.fail(`Error ${err}`);
        });
      return myAction;
    })
  );
```
```js
  // after
  await Promise.all(
    actions.map((name) => {
      return oraPromise(() => doSomeAsyncThing(name), {
        startText: () => `Performing async action ${name}...`,
        successText: (result) => `Success! ${result}`,
        failText: (err) => `Error ${err}`,
      });
    })
  );
```

**Comment by sindresorhus** [comment]
Sounds like a good idea in general. I agree it would be better if it returned the promise instead of the instance. I'm not sure why it's beneficial for it to accept a promise-returning function over just a promise though.

**Comment by vanpipy** [comment]
I agree with the suggestion to enhance the `ora.promise`. 

Follow the code: https://github.com/sindresorhus/ora/blob/498c40ac5676439ceab4707d170d78e41a3f4696/index.js#L394

It can work with a single action only and it is not different between using the `ora` directly. As @sarink said, 

```
ora
  .promise(options)
  .then(actionA)
  .then(actionB)
  .then(actionC)
  .succeed(actionD)
  .failed(actionE)
```

It is a great and different way to use the async `ora`.

**Comment by SrBrahma** [comment]
Couldn't `ora.promise` accept `(() => Promise<void>) | Promise`? I do that in some of my codes. It check if it's a function, and if so, will automatically call it. Having to wrap the given anonymous function and executing it seems unnecessary.

**Comment by SrBrahma** [comment]
Created PR @ https://github.com/sindresorhus/ora/pull/181
