### ISSUE TITLE
when i clone gitlab  code , ora().start('loading'), its stuck...

### ISSUE THREAD

**Issue by zeayal** [sindresorhus/ora#176]
this is not use ora:
![image](https://user-images.githubusercontent.com/28499365/121671002-a1256680-cae0-11eb-9ac3-83b478ef3807.png)

this is use ora:
![image](https://user-images.githubusercontent.com/28499365/121671130-c6b27000-cae0-11eb-9f7a-59d38a644c75.png)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ora#why-does-the-spinner-freeze
