### ISSUE TITLE
Add an updating timestamp before the spinner text

### ISSUE THREAD

**Issue by TeaH4nd** [sindresorhus/ora#178]
I have read abou the prefixText but I can't figure it out how to make it a timestamp like [19:47:35.300] that comes before the spinner icon and text and that keeps updating while the spinner is spinning and when it stops keeps the timestamp of the stopped time. Can someone help me?

**Comment by sindresorhus** [comment]
What have you tried? Show some code and I'm happy to point out how to fix it.
