### ISSUE TITLE
When I run it, I get an error.

### ISSUE THREAD

**Issue by tanmen** [sindresorhus/ora#185]
I just tried to update to 6.0.0 and got an error.
I know that this is due to the fact that package.json states `type: "module"`.
However, I do not understand what is the validity of this.
What should I do?

- PR with an error
   https://github.com/tanmen/disassemble-package/pull/70
- Where the error occurs.
   https://github.com/tanmen/disassemble-package/pull/70/checks?check_run_id=3407154272

### Errors that occur
```
SyntaxError: Cannot use import statement outside a module
```

**Comment by sindresorhus** [comment]
If you click the link in the release notes, it's explained in detail.

**Comment by tanmen** [comment]
I didn't check.
Thank you very much.
