### ISSUE TITLE
Add ability to pass in a Promise

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ora#19]
Many uses of `ora` are waiting on a Promise to finish. Would be nice if you somehow could just pass in a Promise have have it handled by `ora`. This would be especially nice when https://github.com/sindresorhus/ora/issues/8 is implemented, as it would show a success or failure icon depending on the Promise resolve status.

What should the API look like? It could be a sub-method `ora.promise(action)` or an option `ora({promise: action})`.

Thoughts? (Anyone)

**Comment by stephanebachelier** [comment]
@sindresorhus why not `ora.then(action)` ?

**Comment by matheuss** [comment]
Because `something.then(action)` is used when `something` returns a Promise – which is not the case: we want `ora` to **receive** a Promise 😊

**Comment by matheuss** [comment]
_Note: #8 was implemented by #20 ✅_
