### ISSUE TITLE
Using with typescript

### ISSUE THREAD

**Issue by Rxann** [sindresorhus/ora#197]
When I try to use ora with typescript, I get an error when running the compiled file with node.

The error: 

  ```
   const ora_1 = __importDefault(require("ora"));
                              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\GitHub\license-generator\node_modules\ora\index.js from D:\GitHub\license-generator\src\dist\test.js not supported.
Instead change the require of index.js in D:\GitHub\license-generator\src\dist\test.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\GitHub\license-generator\src\dist\test.js:8:31) {
  code: 'ERR_REQUIRE_ESM'
}
 ```

Is this a my code issue or an ESM issue?

**Comment by jason-henriksen** [comment]
This is not an ora problem, but it is a huge hammer to find a correct example of the typescript code.   I have an example working, but I'm in transit today.   I'm hoping to pay it to GitHub tonight and will pay here once it is available.

Ora is a great project.   I'm looking forward to getting the sample up so it can be used more easily.

**Comment by Rxann** [comment]
Thank you so much and whenever you can upload the example that would be great!

**Comment by jason-henriksen** [comment]
Take a look at this boilerplate:  
For me it let's TS and Ora play nice together.

https://github.com/jason-henriksen/typescript-with-esm-no-bable-boilerplate

**Comment by Rxann** [comment]
Thank you for this!

I am just wondering if you know of any other alternatives to this?

**Comment by sindresorhus** [comment]
This is not the place to document how to use ESM with TypeScript. It has nothing specifically to do with Ora.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by jason-henriksen** [comment]
... because roughly 10 people asking "how can I use Ora" clearly has nothing to do with Ora...?

The items under your "Related" section in your readme have nothing specifically to do with Ora either.   
But whatever.   Your project, your call.

@Rxann , I was only looking for a TypeScript-no-babel way to do a native ESM import.  You can message me directly if you have some other specific question about that boiler plate, or make an issue on the boiler plate and I'll see what I can do to help.

**Comment by Rxann** [comment]
Ok sounds good!

**Comment by nephix** [comment]
My workaround:

```
$ npm install ora@^3.2.0 --save-dev
$ npm install @types/ora
```

May miss some features but the API is still pretty simple.

My 2cents on:

> It has nothing specifically to do with Ora

Our codebase already uses ES modules, even in the same script. `ora@6.0.0` is the only one causing trouble

**Comment by Rxann** [comment]
Ok thank you!
