### ISSUE TITLE
Preserve lines

### ISSUE THREAD

**Issue by indeyets** [sindresorhus/ora#2]
It would be nice to keep a log of finished "texts". Can you please add such option?

So, expected result is, that whenever I change the text previous one is preserved on previous line, shifting output further down. Indicator, obviously, should not be preserved :)

**Comment by sholladay** [comment]
I think this can be closed in favor of [listr](https://github.com/SamVerschueren/listr), which wraps this module in an API intended for lists and such, which is the common case where you would want to preserve lines.

**Comment by sindresorhus** [comment]
You can just stop the spinner and start a new one: https://github.com/sindresorhus/ora#stopandpersistoptions
