### ISSUE TITLE
Cannot run inside transpiled cjs files

### ISSUE THREAD

**Issue by cmbirk** [sindresorhus/ora#203]
I'm transpiling my typescript files into commonjs files. When attempting to use ora in the commonjs I get the error:

```
import process from 'node:process';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Would you accept a PR that builds a cjs output as well?

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sindresorhus** [comment]
I have no plans to support CommonJS. Use version 5 if you need CommonJS support.
