### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dcode-denpa** [sindresorhus/ora#208]
Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/bad-bot/node_modules/ora/index.js from /data/data/com.termux/files/home/bad-bot/index.js not supported.
Instead change the require of /data/data/com.termux/files/home/bad-bot/node_modules/ora/index.js in /data/data/com.termux/files/home/bad-bot/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/data/data/com.termux/files/home/bad-bot/index.js:25:13) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
