### ISSUE TITLE
[Feature Request] Support time elapsed as suffix string

### ISSUE THREAD

**Issue by fabriziocucci** [sindresorhus/ora#212]
It would be great if the library could optionally show the time elapsed while the spinner is on, something like:
```
⠋ My very long operation (1m 42s)
```

I'd be happy to contribute this if you think it could be generally useful.

**Comment by sindresorhus** [comment]
I think it's a bit too niche and there are also many other things that could be useful as a suffix. For example, the remaining time of an operation, percentage, etc.

I think a better way to solve this is to introduce a `suffixText` option similar to `prefixText`.

**Comment by fabriziocucci** [comment]
That would be great! :)
