### ISSUE TITLE
Spinner taking a break, then continue

### ISSUE THREAD

**Issue by MoOx** [sindresorhus/ora#25]
![screen shot 2016-09-14 at 09 59 33](https://cloud.githubusercontent.com/assets/157534/18504326/008841b2-7a62-11e6-9ea1-bfdbb15e1734.png)

On the screenshot above, spinner on the left is paused, and you can see the cursor on the right.
But the weird part is that it plays again right before passing to the new symbol (logSymbol.success in my case).

Any idea what can cause this? It's calling a webpack build, so can it be related to the process hanging?

Video: https://files.gitter.im/MoOx/phenomic/dxUG/phenomic.mov

**Comment by matheuss** [comment]
This looks like heavy synchronous I/O operation. Can you provide steps to reproduce?

**Comment by MoOx** [comment]
```
git clone https://github.com/MoOx/phenomic.git
cd phenomic
npm install
npm run docs-start
```

Should do it.

**Comment by MoOx** [comment]
Note that the docs-start is doing another npm install, so don't worry if it takes a couple of minutes :)

**Comment by danielbayerlein** [comment]
Same here, if I run `child_process.execSync`.

**Comment by sindresorhus** [comment]
JavaScript is single-threaded and you're doing a synchronous operation. Nothing else will run when doing `execSync`, including the spinner.

**Comment by danielbayerlein** [comment]
@sindresorhus You are absolutely right! Sorry my mistake.
