### ISSUE TITLE
breaks other `process.on('SIGINT', ...)` handlers

### ISSUE THREAD

**Issue by stefanpenner** [sindresorhus/ora#27]
When using ora, other exit related signal handlers fail to run:

```js
// remove the next line, and "cleanup" prints.
require('ora')('Loading unicorns').start().stop();

process.on('SIGINT', function() {
  // never called if ora was ever enabled
  console.log('cleanup');
});

process.kill(process.pid, 'SIGINT');
```

This is due to: [exit-hook](https://github.com/sindresorhus/exit-hook) used by [restore-cursor](https://github.com/sindresorhus/restore-cursor) not being friendly with other on-exit related strategies.

**Comment by sindresorhus** [comment]
Any ideas on how to resolve this? Maybe re-emit the event in `exit-hook` if there are other SIGINT handlers?

**Comment by stefanpenner** [comment]
> if there are other SIGINT handlers?

can this be detected?

**Comment by sindresorhus** [comment]
```js
process.listenerCount('SIGINT') > 0;
```

https://nodejs.org/api/events.html#events_emitter_listenercount_eventname

**Comment by stefanpenner** [comment]
@sindresorhus that may do the trick

**Comment by stefanpenner** [comment]
@sindresorhus what are your thoughts, should I do ^ on my side regardless or..

**Comment by stefanpenner** [comment]
> @sindresorhus that may should do the trick

Well that actually does not quite do the trick, although it may improve the situation and should be considered.

The scenario is as follows:

Will work 👍 :
```js
require('ora')('Loading unicorns').start().stop();

process.on('SIGINT', function() {
  asyncCleanup().finally(function() {
    process.exit(code);
  });
});
```

Will exit prematurely 👎 :
```js
process.on('SIGINT', function() {
  asyncCleanup().finally(function() {
    process.exit(code);
  });
});
require('ora')('Loading unicorns').start().stop();
```

The reason the last scenario is problematic, is that it now becomes a race: If the async cleanup code is added last, everything will appear to work and if it is added first it will fail to work.

---

Reasoning for async cleanup, is due to (at the very least) windows systems are often quite unhappy with a large number of synchronous `rmdir` and `unlinks`. Although I can imagine other legitimate scenarios where cleanup is inherently async.

**Comment by sindresorhus** [comment]
Ideally, it should handled by `exit-hook`.

To be clear, here's what I was thinking (works):

```js
// `exit-hook`
process.on('SIGINT', () => {
	if (process.listenerCount('SIGINT') === 1) {
		console.log('exit code 2');
		process.exit(2);
	}
});

// your hook
process.on('SIGINT', () => {
	// your async cleanup code
	setTimeout(() => {
		console.log('own sigint');
		process.exit();
	}, 500);
});

setTimeout(() => {
	process.kill(process.pid, 'SIGINT');
}, 1000);
```

**Comment by stefanpenner** [comment]
@sindresorhus ah, the missing bit for me was: `process.listenerCount('SIGINT')` also includes already fired listeners.

**Comment by stefanpenner** [comment]
there may be a further issue:

2 exit-hook libraries (due to npm dupes) may result in deadlock, as they both assume the other will do the cleanup.

**Comment by sindresorhus** [comment]
> Alternatively, making exit-hook guard against being implemented twice via some shared state my enable this to once again work.

Yeah, that could work.

**Comment by sindresorhus** [comment]
Actually, I just remembered that there's another exit hook module that is more comprehensive. We use it in `nyc`. Wonder if switching from `exit-hook` to [`signal-exit`](https://github.com/tapjs/signal-exit) would solve our problems. Mind trying it out? It seems to have a shared emitter: https://github.com/tapjs/signal-exit/blob/6859aff54f5198c63fff91baef279b86026bde69/index.js#L13-L20

**Comment by hjdivad** [comment]
@sindresorhus it looks like `signal-exit` won't handle async cleanup as in @stefanpenner's earlier example

```js
process.on('SIGINT', function() {
  asyncCleanup().finally(function() {
    process.exit(code);
  });
});
```

or have I missed something?

**Comment by sindresorhus** [comment]
@hjdivad I don't know. Did you actually try it?

**Comment by novemberborn** [comment]
One cop-out might be to have an option so that Ora doesn't hide the cursor. You may still want to hide it yourself but you can then also manage hooks yourself.

**Comment by Thomazella** [comment]
Hi! First and foremost thanks for the project. I'm learning how to write spinners for node by looking here 🎉. Also I'd like to give feedback but I don't feel like it needs to be a new issue. Me and a friend ran on this SIGINT issue using Ora, and this thread was the only link between that behavior and the hideCursor option. We weren't understanding why Ora was interfering in killing our CLI using ctrl+c. I think this should be mentioned in the readme, at the very least. Did you guys make hideCursor default to on to avoid introducing a breaking change?

> One cop-out might be to have an option so that Ora doesn't hide the cursor. You may still want to hide it yourself but you can then also manage hooks yourself.

👆🏻That leads me to believe it should default to off.
