### ISSUE TITLE
Multiple simultaneous spinners

### ISSUE THREAD

**Issue by martnst** [sindresorhus/ora#31]
Hi, 

I have a script that tests our REST API running multiple concurrent request. Is it possible to list request line by line with a dedicated spinner at the front of each? In my quick tests, it seems that there can only be one spinner at a time. It seem that creating a second one only updated the text of the first one and so forth. 

Thanks

**Comment by SamVerschueren** [comment]
Maybe [listr](https://github.com/SamVerschueren/listr) is more what you need? It should be possible though by creating multiple instances of Ora.

**Comment by SamVerschueren** [comment]
After thinking this through I don't think it's possible. On mobile so can't test, will have a closer look tomorrow.

**Comment by chrischjh** [comment]
I'm also looking forward to this kind of feature, currently two (or multiple) spinners would display overlapped with each other

**Comment by vinicius0026** [comment]
ping
+1

**Comment by novemberborn** [comment]
Ora is too low-level in its approach to support this feature. @sindresorhus I think this issue should be closed.

**Comment by privatenumber** [comment]
If anyone is interested in doing this, I wanted to share that this can be done via [Ink](https://github.com/vadimdemedes/ink) (React for developing CLIs) pretty trivially.

You can use the [ink-spinner](https://github.com/vadimdemedes/ink-spinner) or [ink-task-runner](https://github.com/privatenumber/ink-task-runner) components.
