### ISSUE TITLE
spinner.stop() let non parseable characters

### ISSUE THREAD

**Issue by danielvieiravega** [sindresorhus/ora#33]
Hi,
 I'm using ora spinner in a cli application. This application generates a json as output, when I redirect this output to a file, several characters are placed inside the file beyond my json. See the attached image:
![output_json](https://cloud.githubusercontent.com/assets/7685159/21767845/7c9fa8e2-d65d-11e6-9e9d-65d8f74cf9cf.PNG)

This behavior makes the output not parseable. 
Any advice in how to handle this problem completely cleaning the console after calling **spinner.stop()**?
Thanks!

**Comment by sindresorhus** [comment]
Fixed. I'll do a new release tomorrow when I've gotten the chance to manually verify with some consumers of the this module.

**Comment by danielvieiravega** [comment]
It worked properly, thank you!
