### ISSUE TITLE
Recurive Loop

### ISSUE THREAD

**Issue by leifdejong** [sindresorhus/ora#38]
Hi, I interestingly managed to create some sort of infinite loop in `ora: 1.1.0`:

```javascript
const ora = require('ora');
const spinner = ora("bash:git fetch --all && git reset --hard origin/develop && git pull origin develop").start();
```

If you omit the "develop" at the end of the string, the problem stops

![bug](https://cloud.githubusercontent.com/assets/1885446/23950122/3214b7da-098a-11e7-914b-63318b353ee8.gif)

**Comment by SamVerschueren** [comment]
It's because the output exceeds the length of the terminal.

**Comment by UnleashedMind** [comment]
I got this as a surprise during an important demo. 
I don't understand the reason on this behavior, why do we need to keep printing if it message exceeds the terminal width?

**Comment by novemberborn** [comment]
Ora currently clears the last line. It doesn't realize that every time it writes, it writes *multiple* lines. Thus it never clears all required lines.
