### ISSUE TITLE
Request: spinner.info([text])

### ISSUE THREAD

**Issue by Seranth** [sindresorhus/ora#39]
Right now there's spinner.succeed([text]) and spinner.fail([text]) where the idea is that it's either a success or a failure e.g. due to an error. I'd like a spinner.info([text]), which ends as something like a yellow !.

I want this because it isn't always the case that a function just succeeds or fail, sometimes you can have e.g. a harmless error that when reached you should be made aware of that it's reached but it hasn't succeeded or failed. 

So spinner.fail would be for "bad" errors, spinner.info would be for "harmless" errors, and spinner.succeed would be for entirely successful runs.

Thoughts?

**Comment by Seranth** [comment]
Just checked the source code and found that you already have spinner.warn, but that it just isn't available yet in NPM. Would you mind updating the npm version with this function? Would be great!

**Comment by sindresorhus** [comment]
Done

**Comment by Seranth** [comment]
Awesome! Can I donate a coffee somewhere? :D
