### ISSUE TITLE
We can't choose spinners on Windows besides the Line Spinner

### ISSUE THREAD

**Issue by koriolis** [sindresorhus/ora#40]
The following line 22 on the Ora constructor always forces the Line spinner on Windows, even if we choose another spinner:

`this.spinner = typeof sp === 'object' ? sp : (process.platform === 'win32' ? cliSpinners.line : (cliSpinners[sp] || cliSpinners.dots)); // eslint-disable-line no-nested-ternary`

I accept it the reasoning to force a different default value for windows instead of `dots` as usually normal unconfigured CMD or PowerShell are not configured to handle most special characters.

Simply blocking the option to select another spinner is a bit excessive in my opinion, and blocks functionality. 

As an example here's VSCode Integrated Terminal with Powershell running the Dots spinner (modified the local Ora code directly):

![ora_dots_spinner](https://cloud.githubusercontent.com/assets/581175/24761539/934cd108-1ae3-11e7-8401-9adbc792a201.gif)

On the other hand if we changed the code above to something like:

`this.spinner = typeof sp === 'object' ? sp : (cliSpinners[sp] || (process.platform === 'win32' ? cliSpinners.line : cliSpinners.dots)); // eslint-disable-line no-nested-ternary`

Then by default Windows gets the `line` spinner, everybody else gets `dots`, but we can **still** choose another spinner in the options if desired.

**Comment by sindresorhus** [comment]
Happy to add better detection for when Unicode is fully supported unconfigured, but the current behavior is intentional so consumers of this module doesn't need to care about having platform conditional code just to specify a spinner.

**Comment by koriolis** [comment]
Fair enough.
But in practice this behaviour also forces the consumers of the module that actually want to display the other spinners in all platforms (say to build an Atom or VSCode plugin or extension just to give you an example) to having to re-define the spinners themselves.
