### ISSUE TITLE
optionally report time taken when spinner ends

### ISSUE THREAD

**Issue by sramam** [sindresorhus/ora#43]
Living on the CLI with complex task sequences of varying lengths, it would be really useful
to have ora optionally print time on the finish calls.

`✔ Create slot SomeText (34s)`

Happy to submit a pull request, but wanted to check if there is an appetite for this ?

**Comment by sindresorhus** [comment]
That is out of scope for Ora. You can set any text you want, including the time elapsed. You might also want to check out: https://github.com/SamVerschueren/listr
