### ISSUE TITLE
Npm deprecations warning when installing

### ISSUE THREAD

**Issue by Nargonath** [sindresorhus/ora#45]
Npm version: 3.10.10
Node version: 6.9.4

![image](https://user-images.githubusercontent.com/583657/28491430-a1f305a8-6ef1-11e7-953d-9e1beab80f48.png)

That's what I get when I `npm install` ora@1.3.0.

I'm not really sure if that's a problem with this package, I tried to google it but to no avail. I checked my package.json, there is no JSON error plus the file is format using prettier so there would be no format error.

Thanks for that great package. :+1:

**Comment by sindresorhus** [comment]
Seems like some kind of corruption in your npm cache. Try removing your `node_modules` folder and run `npm cache clean` and then reinstall. I would also recommend upgrading to latest npm version. For further npm support, use https://github.com/npm/npm/issues

**Comment by Nargonath** [comment]
Alright thanks for the quick answer. Sorry if I misinterpreted the error. Thought it could be a problem of this package. Concerning the latest npm version I'm waiting on node8 to become LTS to switch on it.

You were right, npm cache was the problem. Thank you for you help. Have a good day.

**Comment by sindresorhus** [comment]
You can (and should!) upgrade npm independent of Node.js: `npm i -g npm`

**Comment by Nargonath** [comment]
Oh! My bad! I always considered their versions to be respectively interdependent. Thanks for the info. :+1:
