### ISSUE TITLE
should enabled:false also stop spinner.succeed's output?

### ISSUE THREAD

**Issue by omidfi** [sindresorhus/ora#46]
Hi,  thank you for the awesome spinner! 

I'm setting enabled:false for a specific environment, and I was expecting it also removes any output by spinner.succeed. 
Seems like it's not the case. 

Is it expected behavior or a bug?

**Comment by sindresorhus** [comment]
No, the `spinner.succeed` output is printed after `Ora` is stopped and is just a convenience. It's not the spinner.

**Comment by omidfi** [comment]
Alright thanks again :)
