### ISSUE TITLE
Feature: Progress 

### ISSUE THREAD

**Issue by mattphillips** [sindresorhus/ora#47]
Hey cool project! 

I was using ora and wanted to see the progress of some asynchronous calls but couldn't see a way to adjust the terminal output.

I thought it would be cool if `ora` could accept a `progress` callback - that will be part of the render.

An example usage would be something like:

```js
'use strict';
const Ora = require('.');

let progress = 0;

const timeoutPromise = timeout =>
  new Promise(resolve => {
    setTimeout(() => {
      resolve();
    }, timeout);
  }).then(() => {
    progress++;
  });

const promises = [
  timeoutPromise(1000),
  timeoutPromise(2000),
  timeoutPromise(3000),
  timeoutPromise(300),
  timeoutPromise(4000)
];

const progressCb = () => {
  const percent = Math.round(progress / promises.length * 100);
  return `${percent}/100%`;
};

const spinner = new Ora({
  progress: progressCb,
  text: 'Loading unicorns',
  spinner: process.argv[2]
});

spinner.start();

Promise.all(promises).then(() => spinner.succeed());
```

![progress-demo](https://user-images.githubusercontent.com/5610087/28755593-34630cfc-7556-11e7-8660-4e0f6a78f655.gif)

**Comment by sindresorhus** [comment]
You can already do this with the `.text` property. Why do you feel a new option is needed? See https://github.com/sindresorhus/ora/issues/50#issuecomment-319351090 for a similar request.

**Comment by mattphillips** [comment]
Hey fair point I didn't think to do it with `.text`.

Personally I would rather not mutate the spinner to update the text. I've implemented it locally with mutating `.text` and it means that the spinner needs to be in scope or available to the callback to update the text. 

My solution differs in that the callback doesn't know about the spinner it focuses purely on what it needs to i.e building a progress percentage string in the above example.

I fully appreciate that this might not be a feature that you want built into the library so feel free to close the issue if thats the case. Again cool project :smile: 

_Note: I've just followed the stack of issues/PRs related to this feature (#50, #44, #43, #48) perhaps it's worth making a note on the project that it is a focussed lib and extensions should be wrapped around Ora rather than be baked in?_

**Comment by LinusU** [comment]
Another thought about `progress` being a function, it seems like the most common case will be events that updates the progress status, yet in this design the progress would be polled every frame. Wouldn't it make more sense to set the progress of the spinner, instead of the spinner asking for the progress every frame?
