### ISSUE TITLE
on .start, don't start again if already running

### ISSUE THREAD

**Issue by dylang** [sindresorhus/ora#5]
### Unexpected issue

```js
arrayOfStuff.map( item => {
  spinner.start();
  spinner.text = `do stuff to ${item.name}`;
  // do stuff that might take a while
})
```

In an instance like this where you want to make sure the spinner has started, the spinner does not realize it has already started and will start again and again.

### Expected result

If `spinner.start()` is called multiple times without a `stop`, the extra `start` calls are just ignored.

**Comment by sindresorhus** [comment]
:+1:
