### ISSUE TITLE
Idea: Global prefix & suffix

### ISSUE THREAD

**Issue by jfmmm** [sindresorhus/ora#50]
I think this could be a simple, easy and powerfull solution to #44 

People could implement their own elapsed time feature or in my case I want to show the current memory usage on every line.

ex: 
```js
import util from 'util';
import colors from 'colors';
import filesize from 'filesize';

const spinner = ora({
  text: 'Importing from the database.',
  suffix(){
    return colors.grey(` (Mem used: ${filesize(util.inspect(process.memoryUsage().rss))})`);
  },
  prefix: '­=> '
}).start();
```
would print:
`⠹ => Importing from the database. (Mem used: 98.2mb)`

Barelly add any complexity and it would be pretty versatile.

**Comment by sindresorhus** [comment]
You can already do this with the `text` property. I don't understand why it has to be in Ora.

```js
const changeStatus = text => ora.text = `=> ${text} (Mem used: ${memoryUsed})`;
```

**Comment by jfmmm** [comment]
Welp I tried, fork it is.
