### ISSUE TITLE
flickers in st

### ISSUE THREAD

**Issue by dylnmc** [sindresorhus/ora#52]
Flickers really bad in st (every update). Looks great in urxvt.

Can you maybe use `[CSI]G` (go to beginning of line) rather than updating entire line? Maybe there is no fix. Still a bug.

**Comment by sindresorhus** [comment]
What is `st`? It looks good in the terminals I've tried, so I would guess it's just `st` that is slow.

**Comment by dylnmc** [comment]
http://st.suckless.org/

**Comment by sindresorhus** [comment]
It works fine in all the terminal apps I've tried. It seems it's just `st` being slow.

**Comment by dylnmc** [comment]
sure; just beware it exists, I suppose. I have no use for this software, but I noticed it (and st isn't just any joe-schmoe terminal). Good luck
