### ISSUE TITLE
Issues when used with 'through'

### ISSUE THREAD

**Issue by bitstrider** [sindresorhus/ora#53]
Hi, awesome spinner 👍, definitely adds alot of spice to those boring cli tools

I'm using [`through`](https://github.com/dominictarr/through) in my module and it seems to breaking when I introduce `ora` into the mix.

The following code should write `123` to `number.log`, but it doesn't.

```javascript
const ora = require('ora');
const fs = require('fs')
const through = require('through')

const rs = through();

rs.push('123');
rs.push(null);

const ws = fs.createWriteStream('number.log', { flags: "a" });

rs.pipe(ws)

const spinner = ora("spin").start();
```

However, it works if I use a regular `PassThrough` stream
```javascript
var PassThrough = require('stream').PassThrough;

var rs = new PassThrough;
rs.push('123');
rs.push(null);

const ws = fs.createWriteStream('number.log', { flags: "a" });

rs.pipe(ws);
const spinner = ora("spin").start();

```

Any clue why the incompatibility with `through`?

**Comment by sindresorhus** [comment]
No idea. Would probably be better to ask on the `through` issue tracker. Although you shouldn't be using `through` at all. It's outdated. Instead just use the native streams or [`through2`](https://github.com/rvagg/through2).
