### ISSUE TITLE
The final state doesn't comme out in stdout

### ISSUE THREAD

**Issue by arguiot** [sindresorhus/ora#61]
If you use `ora` in a subprocess, you can't see the animation (which is perfectly normal, but this is not what this issue is about), but when you take the `stdout` of the command, the final state (when you do a `spinner.stop()`) doesn't show in it.

I can't tell you how you can fix it, but I have an idea: when you stop the spinner, you make it disappear, and you `console.log()` the latest frame. I don't know if it will work).

**Comment by s4rbagamble** [comment]
I had a similar issue, where on `spinner.succeed`, the output wasn't being writtent to `stdout` but to `stderr` - this may be your case. I believe you will need to pass the options `{ stream: process.stdout }` to `ora()`.

**Comment by sindresorhus** [comment]
The default stream is `stderr`. You can change this in the options.
