### ISSUE TITLE
Why are all the spinners disabled on win32?

### ISSUE THREAD

**Issue by danielgindi** [sindresorhus/ora#62]
They work fine for me, if I disable the win32 check...

Thanks :-)

**Comment by sindresorhus** [comment]
Duplicate of #40

**Comment by sindresorhus** [comment]
Unicode support in the terminal on Windows is either completely missing, partly supported, and is impossible to detect which reliably, so easier to just do this.

**Comment by pke** [comment]
So what's the status on this after 2 years? Do we still have no reliable way of detecting Unicode in the various Windows shells?
