### ISSUE TITLE
Issues on Windows!

### ISSUE THREAD

**Issue by ahmadawais** [sindresorhus/ora#68]
I just started using this awesome package. Thanks for that.

But it seems that it has some issues on windows. Using it in the #0CJS [`create-guten-block`](https://github.com/ahmadawais/create-guten-block) package.

Here's the issue https://github.com/ahmadawais/create-guten-block/issues/6

```js
TypeError: this.stream.clearLine is not a function
```
Kindly, take a look.

Which is why on Windows I have to do this

```js

const isWindows = require( 'is-windows' );
const ora = isWindows() ? false : require( 'ora' );

// Init the spinner.
	const spinner = ora ? new ora( { text: '', enabled: true } ) : false;

if ( spinner ) {
		spinner.start(
			`1. Creating the plugin directory called → ${ chalk.black.bgWhite(
				` ${ blockName } `
			) }`
		);
	} else {
		console.log(
			chalk.green( ' 1. Creating the plugin directory called → ' ) +
				chalk.black.bgWhite( ` ${ blockName } ` )
		);
	}

await createPluginDir( blockName );

	if ( spinner ) {
		spinner.succeed();
	}
```

Which as you can see is less than ideal.

**Comment by sindresorhus** [comment]
Why are you using the `enabled` option? You're basically forcing it to be enabled when the auto-detection would have turned it off since it's not supported.

**Comment by ahmadawais** [comment]
@sindresorhus oh boy! Silly me!
Thanks for that. Just refactored the code and pushed an update.

👏
