### ISSUE TITLE
Release notes for 2.0.0

### ISSUE THREAD

**Issue by d4nyll** [sindresorhus/ora#70]
Since the [2.0.0](https://github.com/sindresorhus/ora/releases/tag/v2.0.0) release is a bump in the major version from the previous version, can you provide some release notes for it? Especially what's breaking and how an user can migrate from `1.4.0` to `2.0.0`.

Thanks.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/ora/releases/tag/v2.0.0
