### ISSUE TITLE
After v1.2.0 bats tests break 

### ISSUE THREAD

**Issue by omidfi** [sindresorhus/ora#71]
I'm using [bats](https://github.com/sstephenson/bats) to test my cli app [moro](https://github.com/omidfi/moro). 

Bats runs end to end tests just like a shell script. 

I know in CI and when there's no TTY, ora gets disabled. But I can't figure out why it was working in v1.2.0?  

Let me try to create a test case

```javascript
// utils/spinner.js
const ora = require('ora')
const mainSpinner = ora({
  text: '',
  spinner: 'flip',
  color: 'red'
})

module.exports = mainSpinner
```

Then somewhere else

```javascript
const spinner = require('./utils/spinner.js')

spinner.start()
// ... do some stuff

spinner.succeed(`You clocked in successfully`).start()
```

In version ora@1.2.0 this command works by this bats test file: 
```bash
@test "it says You clocked in" {
  run faketime '2020-01-01 08:00:00' moro
  assert_success
  assert_output_contains 'You clocked in'
}
```

But in ora@1.4.0 it just prints nothing, as spinner.enabled is undefined. 

Any ideas would be appreciated :)

**Comment by sindresorhus** [comment]
Submit a pull request with a [failing test](https://github.com/avajs/ava#failing-tests) and I'll take a closer look. I'm requesting this as most issues like these are just users using the module incorrectly or an unrelated problem.

**Comment by omidfi** [comment]
I couldn't make the failing test so probably it's what you said. Closing this for now. Thanks for all the awesome things you add to the world. Highly appreciated :)
