### ISSUE TITLE
Get spinner.isSpinning

### ISSUE THREAD

**Issue by xavdid** [sindresorhus/ora#72]
It would be great to get a bool to see if an instance of the spinner is currently spinning. 

I read through the code (surprisingly small lib for how much it does!) and it seems like we can functionally read `spinner.id`, which will be null if that instance is not spinning and truthy otherwise. 

I'm happy to write some logic around this, but since it's not explicitly documented, I wanted to double check that this is a good way to do it and the functionality won't disappear. 

thanks!

**Comment by sindresorhus** [comment]
What's the use-case? What do you need it for?

**Comment by xavdid** [comment]
We have a series of steps that use spinners. At the end, there's a method that calls a final `.succeed` or `.fail`. Mostly fine, but if there's an error before the first spinner starts, then the final call prints a single X with no text because it's stopping and persisting a spinner which wasn't spinning. 

The fixed version returns early if the spinner was stopped, before it calls `.fail`

**Comment by sindresorhus** [comment]
Alright. PR welcome for a `.isSpinning` getter property.

**Comment by xavdid** [comment]
Happy to write it. Is it functionally equivalent to `.id`?

**Comment by SamVerschueren** [comment]
You should use a getter property like [`text`](https://github.com/sindresorhus/ora/blob/master/index.js#L45-L47). Or do you mean, if `id` is set, does it mean it is spinning? I guess it is because then an interval is set.

**Comment by sindresorhus** [comment]
Fixed by #73
