### ISSUE TITLE
fails to clear when the line length is too long

### ISSUE THREAD

**Issue by feiyuerenhai** [sindresorhus/ora#74]
fails to clear current line when the line length is too long, to be exactly, more than process.stdout.columns. for example, when I set spinner.text = 'abracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebraabracadebra', spinner refuses to clear but moves to the next line, leaving last line dead ...

<img width="564" alt="dingtalk20180312165630" src="https://user-images.githubusercontent.com/15189212/37273987-55e69292-2616-11e8-8ee2-70966c44cbfa.png">

updated on 12 Mar, 19:01: by viewing the source code, now I know the solution is to break input into lines according to terminal.columns ......

**Comment by sindresorhus** [comment]
Should be fixed by https://github.com/sindresorhus/ora/commit/4df5d19a5aa373775d210a7549704d5c882dec1a
