### ISSUE TITLE
Multiple instances simultaneously?

### ISSUE THREAD

**Issue by FizzyGalacticus** [sindresorhus/ora#76]
I cannot find anything in the code/documentation about being able to use multiple `ora` instances at the same time. This would be very handy when displaying statuses of multiple async operations. For instance, `yarn` does something similar with the spinning slashes when adding or updating dependencies.

**Comment by artfuldev** [comment]
I think this is a duplicate of #31

**Comment by FizzyGalacticus** [comment]
Yeah, it is. Thanks!
