### ISSUE TITLE
Add new methods .succeed() and .fail()?

### ISSUE THREAD

**Issue by maxrimue** [sindresorhus/ora#8]
Hey,
first of all, great module! Love it.

I thought that since this module is meant to display progress in something, wouldn't it make sense to also display whether that succeeds or fails?

What I'm imagining is 1) a method `.suceed()` that turns the spinner into a green tick, and 2) a method `.fail()` that turns the spinner into a red cross (and possibly the text, too?).

What does everyone think about this?

**Comment by SamVerschueren** [comment]
I'm going to implement this in one of the following days if that's ok to you @sindresorhus? Could use that in [listr](https://github.com/SamVerschueren/listr) because I already use `ora`, but only for the spinner. It would be nice of `ora` could handle an entire line.

**Comment by sindresorhus** [comment]
@SamVerschueren Go ahead :)
