### ISSUE TITLE
Spinner pauses when using `child_process.execSync`

### ISSUE THREAD

**Issue by TotomInc** [sindresorhus/ora#86]
Spinner pauses when I start a command using `child_process.execSync`.

Is this intended? Did I need to manually render the frames using `ora.render()`?

**Comment by sindresorhus** [comment]
JavaScript is single-threaded, so running a synchronous function blocks everything else, including Ora. Use `exec` instead.

**Comment by jediyozh** [comment]
If so, why it does work and doesn't pause the spinner?

```
async function run() {
  spinner.start('Installing packages...');
  await install('npm install');
  spinner.succeed('Installed');
}

function install() {
  return new Promise((resolve, reject) => {
    exec('npm install').on('close', code => {
      if (code === 0) {
        resolve();
      }
      reject();
    });
  });
}

run();
```

**Comment by sindresorhus** [comment]
@jediyozh Because `exec` is asynchronous, not synchronous.

**Comment by jediyozh** [comment]
@sindresorhus of course but I made it synchronous with Promise, no?

**Comment by sindresorhus** [comment]
@jediyozh No. I would recommend reading up on how promises and async/await work. In short, `await` only pauses the execution context of the function, not the whole process.

**Comment by jediyozh** [comment]
@sindresorhus Got it. Thanks for the explanation and for the great tool 👍

**Comment by sindresorhus** [comment]
Also, I would recommend [`execa`](https://github.com/sindresorhus/execa) instead of `exec`. It's Promise-friendly and more user-friendly.

**Comment by jediyozh** [comment]
@sindresorhus I will look at this

**Comment by famanoder** [comment]
👍
