### ISSUE TITLE
only enable when this.stream.clearLine is available

### ISSUE THREAD

**Issue by dylang** [sindresorhus/ora#9]
### Issue

When spawning a command that uses `ora`, `stream.clearLine` isn't available. This causes ora to throw an exception when it runs `this.stream.clearLine();`. 

I'm guessing there are other times `clearLine` may not be available.

### Possible solution

The `enable` check could include checking that `this.stream.clearLine` is a function, or maybe `this.stream.isTTY` is `true`.

**Comment by sindresorhus** [comment]
Weird. It's already checking `this.stream.isTTY` before using `clearLine`. https://github.com/sindresorhus/ora/blob/ca4e8eaaee67010fab34f02a1031aafa27ebc0a8/index.js#L37

**Comment by dylang** [comment]
My own bug! 

I am setting `spinner.enabled` every time I use it and not respecting if it's possible to be enabled.  

Thanks for taking a look at this issue and hope I didn't take too much of your time.

**Comment by sindresorhus** [comment]
No worries at all. You always provide really good bug reports :)
