### ISSUE TITLE
Change patreon to private donation

### ISSUE THREAD

**Issue by brutalcrozt** [sindresorhus/ora#99]
I don't have any intention to do any harm.
But i think we need to discuss this one.

Please see this video on your free time
[![](https://img.youtube.com/vi/h8_OrrvaVVw/0.jpg)](https://www.youtube.com/watch?v=h8_OrrvaVVw)<br>

Then we can start the discussion

**Comment by sindresorhus** [comment]
Sorry, I’m not going to watch a random video without any context.

I have other donation options if Patreon is not for you: https://sindresorhus.com/donate :)
